
# <center> Escuela Politécnica Nacional </center>

**Nombre:** Francisco Ulloa<br>
**Fecha:** Quito, 20 de enero de 2026<br>
**Tema:** Factorización LU<br>
**Repositorio:**<br>
https://github.com/Fu5CHAR/Metodos_numericos_2025B_Ulloa-Francisco/tree/main

**1. Realice las siguientes multiplicaciones matriz-matriz:**
$$
a. \begin{bmatrix}
&2 &-3\\
&3 & -1
\end{bmatrix}

\begin{bmatrix}
&1 & 5\\
&2 & 0
\end{bmatrix}
$$

$$
b. \begin{bmatrix}
&2 &-3\\
&3 & -1
\end{bmatrix}

\begin{bmatrix}
&1 & 5 &-4\\
&-3 & 2 &0
\end{bmatrix}
$$

$$
c. \begin{bmatrix}
&2 &-3 &1\\
&4 & 3 &1\\
&5 &2 &-4
\end{bmatrix}

\begin{bmatrix}
&0 & 1 &-2\\
&1 & 0 &-1\\
&2 &3 &-2
\end{bmatrix}
$$

$$
d. \begin{bmatrix}
&2 &1 &2\\
&-2 & 3 &0\\
&2 &-1 &3
\end{bmatrix}

\begin{bmatrix}
&1 & -2\\
&-4 & 1\\
&0 &2
\end{bmatrix}
$$



In [44]:
import numpy as np
A1= np.array([[2, -3],[3, -1]])
A2=np.array([[1, 5],[2,0]])
B1=np.array([[2, -3],[3, -1]])
B2=np.array([[1, 5, -4],[-3,2,0]])
C1=np.array([[2,-3,1],[4,3,1],[5,2,-4]])
C2=np.array([[0,1,-2],[1,0,-1],[2,3,-2]])
D1=np.array([[2,1,2],[-2,3,0],[2,-1,3]])
D2=np.array([[1,-2],[-4,1],[0,2]])

resultadoA1_A2 = A1 @ A2
print("Resultado de A1 * A2:\n", resultadoA1_A2)
resultadoB1_B2 = B1 @ B2
print("Resultado de B1 * B2:\n", resultadoB1_B2)
resultadoC1_C2 = C1 @ C2
print("Resultado de C1 * C2:\n", resultadoC1_C2)
resultadoD1_D2 = D1 @ D2
print("Resultado de D1 * D2:\n", resultadoD1_D2)


Resultado de A1 * A2:
 [[-4 10]
 [ 1 15]]
Resultado de B1 * B2:
 [[ 11   4  -8]
 [  6  13 -12]]
Resultado de C1 * C2:
 [[ -1   5  -3]
 [  5   7 -13]
 [ -6  -7  -4]]
Resultado de D1 * D2:
 [[ -2   1]
 [-14   7]
 [  6   1]]


**2. Determine cuáles de las siguientes matrices son no singulares y calcule la inversa de esas matrices**
$$
a. \begin{bmatrix}
&4 &2 &6\\
&3 &0 &7\\
&-2 &-1 &-3
\end{bmatrix}

b. \begin{bmatrix}
&1 &2 &0\\
&2 &1 &-1\\
&3 &1 &1
\end{bmatrix}
\\\\
$$
$$
\\\\
c. \begin{bmatrix}
&1 &1 &-1 &1\\
&1 &2 &-4 &-2\\
&2 &1 &1 &5\\
&-1 &0 &-2 &-4
\end{bmatrix}

d. \begin{bmatrix}
&4 &0 &0 &0\\
&6 &7 &0 &0\\
&9 &11 &1 &0\\
&5 &4 &1 &1
\end{bmatrix}
$$

In [45]:
import numpy as np
A=np.array([[4,2,6],[3,0,7],[-2,-1,-3]])
B=np.array([[1,2,0],[2,1,-1],[3,1,1]])
C=np.array([[1,1,-1,1],[1,2,-4,-2],[2,1,1,5],[-1,0,2,-4]])
D=np.array([[4,0,0,0],[6,7,0,0],[9,11,1,0],[5,4,1,1]])
def invert_matrix(matrix):
    if np.linalg.det(matrix) != 0:
        inv_matrix = np.linalg.inv(matrix)
        return print('La matriz :\n', matrix, '\nes no singular y la inversa de la matriz es:\n', inv_matrix)
    else:
        return print("La matriz:\n", matrix, "\nes singular y no tiene inversa.")
    
invert_matrix(A)
invert_matrix(B)
invert_matrix(C)
invert_matrix(D)


La matriz:
 [[ 4  2  6]
 [ 3  0  7]
 [-2 -1 -3]] 
es singular y no tiene inversa.
La matriz :
 [[ 1  2  0]
 [ 2  1 -1]
 [ 3  1  1]] 
es no singular y la inversa de la matriz es:
 [[-0.25   0.25   0.25 ]
 [ 0.625 -0.125 -0.125]
 [ 0.125 -0.625  0.375]]
La matriz:
 [[ 1  1 -1  1]
 [ 1  2 -4 -2]
 [ 2  1  1  5]
 [-1  0  2 -4]] 
es singular y no tiene inversa.
La matriz :
 [[ 4  0  0  0]
 [ 6  7  0  0]
 [ 9 11  1  0]
 [ 5  4  1  1]] 
es no singular y la inversa de la matriz es:
 [[ 0.25        0.          0.          0.        ]
 [-0.21428571  0.14285714 -0.         -0.        ]
 [ 0.10714286 -1.57142857  1.         -0.        ]
 [-0.5         1.         -1.          1.        ]]


**3. Resuelva los sistemas lineales 4x4 que tienen la misma matriz de coeficientes:**
$$
S1:
\begin{matrix}
&x_1 &-x_2 &+x_3 &-x_4 &= 6\\
&x_1 & &-x_3 &+x_4 &=4\\
&2x_1 &+x_2 &+3x_3 &-4x_4 &=-2\\
& &-x_2 &+x_3 &-x4 &= 5 
\end{matrix}
$$
$$
S2:
\begin{matrix}
&x_1 &-x_2 &+x_3 &-x_4 &= 1\\
&x_1 & &-x_3 &+x_4 &=1\\
&2x_1 &+x_2 &+3x_3 &-4x_4 &=2\\
& &-x_2 &+x_3 &-x4 &= -1 
\end{matrix}
$$

In [46]:
matriz = np.array([[1,-1,2,-1],[1,0,-1,1],[2,1,3,-4],[0,-1,1,-1]])
b1= np.array([6,4,-2,5])
b2= np.array([1,1,2,-1])
inv_matrix = np.linalg.inv(matriz)
solucion1 = inv_matrix @ b1
print("Solución del sistema 1:\n", solucion1)
solucion2 = inv_matrix @ b2
print("Solución del sistema 2:\n", solucion2)

Solución del sistema 1:
 [ 3. -6. -2. -1.]
Solución del sistema 2:
 [1. 1. 1. 1.]


**4. Encuentre los valores de A que hacen que la siguiente matriz sea singular.**
$$
A= 
\begin{bmatrix}
&1 & -1 & \alpha\\
&2 &2 &1\\
&0 &\alpha & \frac{-3}{2}
\end{bmatrix}
$$

Para que una matriz sea singular, esta no debe ser invertible, es decir, su determinante debe ser igual a cero.<br>
Entonces buscamos los valores de $\alpha$ tal que $det[A]=0$.<br>
Luego,

\begin{equation*}
\begin{split}
det[A] &= ((1 * 2 *\frac{-3}{2})+(2 * \alpha * \alpha)+(0 * 1 * -1)) -((\alpha * 2 * 0)+(1 * \alpha * 1)+(\frac{-3}{2} * 2 * -1))\\
&= (-3+2(\alpha)^2 + 0) - (0 + \alpha + 3)\\
&= 2(\alpha)^2 - \alpha - 6
\end{split}
\end{equation*}
<br>

Si $det(A)=0$, entonces<br>

\begin{equation*}
\begin{split}
2(\alpha)^2 - \alpha - 6 &=0\\
(\alpha -3)(\alpha +2) &= 0
\end{split}
\end{equation*}
<br>

Finalmente, la matriz A es singular para $\alpha=3$ y $\alpha=-2$.

**Resuleva los siguientes sistemas lineales:**
$$
a. 
\begin{bmatrix}
1 &0 &0\\
2 &1 &0\\
-1 &0 &1
\end{bmatrix}
\begin{bmatrix}
2 &3 &-1\\
0 &-2 &-1\\
0 &0 &3
\end{bmatrix}
\begin{bmatrix}
x_1 \\x_2 \\x_3
\end{bmatrix}
=\begin{bmatrix}
2 \\-1 \\1
\end{bmatrix}
$$
$$
b. 
\begin{bmatrix}
2 &0 &0\\
-1 &1 &0\\
3 &2 &-1
\end{bmatrix}
\begin{bmatrix}
1 &1 &1\\
0 &1 &2\\
0 &0 &1
\end{bmatrix}
\begin{bmatrix}
x_1 \\x_2 \\x_3
\end{bmatrix}
=\begin{bmatrix}
-1 \\3 \\0
\end{bmatrix}
$$

Tenemos sistemas lineales escritos de la forma: $LUx = y$. Ahora, definimos 
$Ux = y$, entonces $Ly = b$.<br>
Primero, resolvemos $y$ de la ecuación $Ly = b$. Donde:<br>
$$ 
\begin{bmatrix}
1 &0 &0\\
2 &1 &0\\
-1 &0 &1
\end{bmatrix}
\begin{bmatrix}
y_1 \\y_2 \\y_3
\end{bmatrix}
=\begin{bmatrix}
2 \\-1 \\1
\end{bmatrix}
$$

Luego, <br>
$$
\begin{equation*}
y_1 = 2
\end{equation*}\\\\
\begin{equation*}
\begin{split}
y_2 &= -2y_1 - 1\\
&=-2(1) + 1\\
&=-3
\end{split}
\end{equation*}\\\\
\begin{equation*}
\begin{split}
y_3 &= \frac{1y_1 - 0y_2 +1}{3}\\
&=\frac{1(1) - 0(-3)+1}{3}\\
&=\frac{2}{3}
\end{split}
\end{equation*}
$$

Ahora, conseguimos $x$ de $Ux=y$. Donde:<br>
$$
\begin{bmatrix}
2 &3 &-1\\
0 &-2 &-1\\
0 &0 &3
\end{bmatrix}
\begin{bmatrix}
x_1 \\x_2 \\x_3
\end{bmatrix}
=\begin{bmatrix}
2 \\-3 \\ \frac{2}{3}
\end{bmatrix},
$$

entonces:<br>
$$
\begin{equation*}
x_3 = \frac{2}{9}
\end{equation*}\\\\
\begin{equation*}
\begin{split}
x_2 &= -2y_1 - 1\\
&=-2(1) + 1\\
&=-3
\end{split}
\end{equation*}\\\\
\begin{equation*}
\begin{split}
y_3 &= \frac{1y_1 - 0y_2 +1}{3}\\
&=\frac{1(1) - 0(-3)+1}{3}\\
&=\frac{2}{3}
\end{split}
\end{equation*}
$$
